Above are layers in this Program
Embedding :Embedding is used to convert text data or any type of data into the vecotrs format instedad of 0s and 1s

LSTM : Long Short Term Memory have memory celss tha can store and retrive information over long sequence, allowing them to capture dependancies in data.It uses gates(input,forget,output gates) to regulate the flow of information

Dense: Dense is  neural network in which the neuron or node is connected to the every neuron in the preivous layer. It provides a high degree of connectivity between neurons,allowing neural network to learn and model comples relationships in data during the training process

Above are preprocssing
One-Hot_Encoding : It is used to represent categorical variables numerivally. encoded in each unique categoy or label is represent by binary vector, where elements are zero except for the index that coreesponds to the category 

In [1]:
import tensorflow as tf 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM 
from tensorflow.keras.layers import Dense 
from tensorflow.keras.preprocessing.text import one_hot 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

Preprocessing the text
re: Regressor is used for the String Manipulation 

nltk : Natural Language Toolkit(NLTK) is used for human language data

stopwords: the 'stopwords' corpus is collectoin of common words that are often considered to be littel value in text analysis , this are used to filter out the text because there are common words and don't have meaning, EG. "the", "and", "is", "in", etc

PortStemer: Provides a stemming algorithm that reduces words to their base or root form by removing suffixes. Reducing words to their base or root form to simplify text analysis

In [2]:
import re 
import nltk 
from nltk.corpus import stopwords 
from nltk.stem.porter import PorterStemmer
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\tmachine\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
import pandas as pd 
data = pd.read_csv('train.csv')
data.head(10)

id                                              title  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2   2                  Why the Truth Might Get You Fired   
3   3  15 Civilians Killed In Single US Airstrike Hav...   
4   4  Iranian woman jailed for fictional unpublished...   
5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6   6  Life: Life Of Luxury: Elton John’s 6 Favorite ...   
7   7  Benoît Hamon Wins French Socialist Party’s Pre...   
8   8  Excerpts From a Draft Script for Donald Trump’...   
9   9  A Back-Channel Plan for Ukraine and Russia, Co...   

                         author  \
0                 Darrell Lucus   
1               Daniel J. Flynn   
2            Consortiumnews.com   
3               Jessica Purkiss   
4                Howard Portnoy   
5               Daniel Nussbaum   
6                           NaN   
7               Alissa J. Rubin   
8                           NaN   
9  Megan Twohey and Scott Shane   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1  
5  In these trying times, Jackie Mason is the Voi...      0  
6  Ever wonder how Britain’s most iconic pop pian...      1  
7  PARIS  —   France chose an idealistic, traditi...      0  
8  Donald J. Trump is scheduled to make a highly ...      0  
9  A week before Michael T. Flynn resigned as nat...      0

Removing the NaN values from the dataset

It removing all the null values and reset the index value from the beginning 


In [4]:
data = data.dropna()
data.reset_index(inplace=True)

Extracting the Dependant and Independant Variables from the data


In [5]:
X = data.drop("label", axis=1)
y=data["label"]

In [6]:
print(X.shape)
print(y.shape)


(18285, 5)
(18285,)


1 copying the train data to messages variable so no modifyling oocur for original
2 creating the object for PortStemmer
3 creating a empty list so that the preprocessed data will be added 
4 initalizing a for loop to iterate into entire message 
5 using review variable and re it will substitude the character with " " if incase not from a to z and this will be done in the messages['title']
6 lowering all characer 
7 spliting the words for stemming 
8 initializing another for loop if the words having the comming words like "but' "is" "and" will be removed using the for looop
9 joining all the words into the review 
10 appending with the empty list 


In [7]:
messages = X.copy()
ps = PorterStemmer()
corpus = []
for i in range(len(messages)):
    review = re.sub("[^a-zA-Z]"," ", messages['title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in  stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

One Hot Encoding 
processing each words by words with size of 5000 to process the onehot encoding 


In [8]:
vocab_size =5000
onehot_repr = [one_hot(words,vocab_size) for words in corpus]
onehot_repr

[[1831, 2439, 4661, 2871, 940, 4264, 655, 2263, 1078, 2360],
 [2284, 2772, 4125, 1823, 3661, 2747, 3321],
 [1927, 4729, 2759, 3301],
 [1168, 4092, 3102, 2130, 3664, 389],
 [3566, 3661, 2534, 1653, 961, 4860, 3661, 2995, 1583, 1061],
 [3542,
  2789,
  147,
  2120,
  3589,
  4536,
  4678,
  1197,
  1551,
  918,
  4005,
  3545,
  1350,
  3949,
  3321],
 [4924, 1336, 1502, 2202, 3015, 2478, 2053, 668, 3847, 4840, 4519],
 [4614, 1035, 3477, 930, 1699, 760, 4536, 3284, 3847, 4840, 4519],
 [1878, 4681, 3010, 4190, 1462, 4442, 3663, 2387, 4536, 436],
 [1694, 4105, 1800, 3907, 453, 3128, 237, 2965],
 [1511, 2586, 1359, 2628, 2260, 1988, 2971, 1775, 1971, 409, 35],
 [2130, 2846, 940, 4442, 4536, 1699],
 [1632, 1332, 2742, 3355, 3701, 1368, 184, 2133, 606],
 [2491, 2295, 553, 3766, 1887, 2790, 144, 3847, 4840, 4519],
 [114, 2298, 989, 826, 3680, 3847, 4840, 4519],
 [3837, 4218, 282, 3391, 3463, 2535, 3704, 3634, 3347, 1157],
 [4568, 2018, 2772],
 [485, 4236, 4427, 7, 4536, 221, 2175, 3321],
 [177

Applying the Pad Seqences to make sentence length Equal
1  giving the maximum sentence length has 20 
2  using pad_sequences we are padding it with zero , (here padding='pre' indicate adding of 0 in front post means adding back with maxlength of 20 )

In [9]:
sent_length=20
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2263 1078 2360]
 [   0    0    0 ... 3661 2747 3321]
 [   0    0    0 ... 4729 2759 3301]
 ...
 [   0    0    0 ... 3847 4840 4519]
 [   0    0    0 ... 1814 3267  937]
 [   0    0    0 ... 1027 1633 3013]]


Creating a Model 


1 : This variable represents the dimensionality of the vector space in which words will be embedded 
2 : initializing a sequential model using keras. A sequenial Model is appropriate for a plain stack of layers where each layer has exactly one input tensor and one outpur tensor 
3 : Adds an embeding layer to model, (vocab_size) the number of uniqe words in the input data ,(embedded vector feature ) dimensity of the embedding vector , length of the input sequences, THis is crucial for LSTM 
4 : adding a LSTm with sigmoid which means output either 1 or 0 

In [10]:
embedding_vector_features =40 
model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy'])
print(model.summary())



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


Training and Testing the Data


In [11]:
import numpy as np 
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X_final, y_final, test_size=0.3, random_state=42)

here we are fitting the training data with our model and then , giving a validation_data with the test data which is used to valid and give the accuracy of the data by performing it into our model , epochs has 10 , during the training data divided into smaller batches. The batch size is the number of training examples used in one iteration. 

In [14]:
model.fit(X_train, y_train, validation_data=(X_test,y_test,), epochs=10, batch_size=64)

Epoch 1/10


200/200 [==============================] - 3s 9ms/step - loss: 0.3218 - accuracy: 0.8494 - val_loss: 0.1966 - val_accuracy: 0.9172
Epoch 2/10
200/200 [==============================] - 2s 8ms/step - loss: 0.1357 - accuracy: 0.9472 - val_loss: 0.1980 - val_accuracy: 0.9189
Epoch 3/10
200/200 [==============================] - 2s 8ms/step - loss: 0.0980 - accuracy: 0.9631 - val_loss: 0.2241 - val_accuracy: 0.9189
Epoch 4/10
200/200 [==============================] - 2s 8ms/step - loss: 0.0770 - accuracy: 0.9717 - val_loss: 0.2496 - val_accuracy: 0.9072
Epoch 5/10
200/200 [==============================] - 2s 8ms/step - loss: 0.0555 - accuracy: 0.9802 - val_loss: 0.2928 - val_accuracy: 0.9085
Epoch 6/10
200/200 [==============================] - 2s 8ms/step - loss: 0.0401 - accuracy: 0.9872 - val_loss: 0.4170 - val_accuracy: 0.8992
Epoch 7/10
200/200 [==============================] - 2s 8ms/step - loss: 0.0270 - accuracy: 0.9916 - val_loss: 0.4257 - val_accuracy: 0.9098
Epoc

Performance Metrics and Accuracy


In [17]:
y_pred = model.predict(X_test)
y_pred = np.round(y_pred).astype(int)
from sklearn.metrics import confusion_matrix 
confusion_matrix(y_test,y_pred)

172/172 [==============================] - 0s 2ms/step


array([[2875,  232],
       [ 292, 2087]], dtype=int64)

In [18]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9044841414509661